version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=sim
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=simdb
    ports:
      - "3306:3306"
    

  soap_emulator:
    container_name: soap_emulator
    build:
      context: .
      dockerfile: soap_emulator/Dockerfile
    ports:
      - "10101:10101"
    

  flask-app:
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - soap_emulator
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user:user_password@mysql/test_db


